#!/usr/bin/env python
import argparse
import psutil

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('-d', metavar='<mount point>', default='/', help='which mountpoint to check')

args = parser.parse_args()

disk   = psutil.disk_usage(args.d)


gauges = {
    "used":     disk.used,
    "total":     disk.total,
}
    
for name, value in gauges.items():
    print name, value